#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <QString>

const QString CONFIG_DIR = "etc";
const QString LOG_CFG_FILE = "etc/log4j.properties";
const QString INI_FILE = "etc/config.ini";
const QString APPLICATION_NAME = "PDM - GUI for Pulsar";
const QString ORGANIZATION_NAME = "lakala";
const QString APPLICATION_VERSION = "1.0.2";

const QString SERVICE_HOST_KEY = "PULSAR_SERVICE_HOST/HOST";
const QString FUNCTION_HOST_KEY = "PULSAR_FUNCTION_HOST/HOST";
const QString PRESTO_HOST_KEY = "PULSAR_PRESTO_HOST/HOST";
const QString GET_TENANTS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_TENANTS_PATH";
const QString GET_NAMESPACES_PATH_KEY = "PULSAR_SERVICE_PATH/GET_NAMESPACES_PATH";
const QString GET_CLUSTERS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_CLUSTERS_PATH";
const QString GET_BROKER_SRV_PATH_KEY = "PULSAR_SERVICE_PATH/GET_BROKER_SRV_PATH";
const QString PUT_NEW_TENANT_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_TENANT_PATH";
const QString DELETE_TENANT_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_TENANT_PATH";
const QString PUT_NEW_NAMESPACE_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_NAMESPACE_PATH";
const QString DELETE_NAMESPACE_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_NAMESPACE_PATH";
const QString GET_TOPIC_STATS_KEY = "PULSAR_SERVICE_PATH/GET_TOPIC_STATS_PATH";
const QString GET_TOPICS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_TOPICS_PATH";
const QString GET_PARTITIONED_TOPICS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_PARTITIONED_TOPICS_PATH";
const QString GET_PARTITIONS_TOPIC_PATH_KEY = "PULSAR_SERVICE_PATH/GET_PARTITIONS_TOPIC_PATH";
const QString PUT_NEW_NONPARTITIONED_TOPIC_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_NONPARTITIONED_TOPIC_PATH";
const QString PUT_NEW_PARTITIONED_TOPIC_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_PARTITIONED_TOPIC_PATH";
const QString DELETE_TOPIC_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_TOPIC_PATH";
const QString DELETE_PARTITIONED_TOPIC_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_PARTITIONED_TOPIC_PATH";
const QString GET_LAST_MESSAGE_ID_PATH_KEY = "PULSAR_SERVICE_PATH/GET_LAST_MESSAGE_ID_PATH";
const QString GET_MESSAGE_PATH_KEY = "PULSAR_SERVICE_PATH/GET_MESSAGE_PATH";
const QString GET_FUNCTIONS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_FUNCTIONS_PATH";
const QString GET_FUNCTION_STATUS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_FUNCTION_STATUS_PATH";
const QString PUT_NEW_FUNCTION_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_FUNCTION_PATH";
const QString DELETE_FUNCTION_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_FUNCTION_PATH";
const QString START_FUNCTION_PATH_KEY = "PULSAR_SERVICE_PATH/START_FUNCTION_PATH";
const QString STOP_FUNCTION_PATH_KEY = "PULSAR_SERVICE_PATH/STOP_FUNCTION_PATH";
const QString GET_NAMESPACE_PERMISSIONS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_NAMESPACE_PERMISSIONS_PATH";
const QString REVOKE_NAMESPACE_PERMISSION_PATH_KEY = "PULSAR_SERVICE_PATH/REVOKE_NAMESPACE_PERMISSION_PATH";
const QString GRANT_NAMESPACE_PERMISSION_PATH_KEY = "PULSAR_SERVICE_PATH/GRANT_NAMESPACE_PERMISSION_PATH";
const QString GET_SOURCES_PATH_KEY = "PULSAR_SERVICE_PATH/GET_SOURCES_PATH";
const QString GET_SOURCE_INFO_PATH_KEY = "PULSAR_SERVICE_PATH/GET_SOURCE_INFO_PATH";
const QString GET_SOURCE_STATUS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_SOURCE_STATUS_PATH";
const QString PUT_NEW_SOURCE_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_SOURCE_PATH";
const QString DELETE_SOURCE_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_SOURCE_PATH";
const QString START_SOURCE_PATH_KEY = "PULSAR_SERVICE_PATH/START_SOURCE_PATH";
const QString STOP_SOURCE_PATH_KEY = "PULSAR_SERVICE_PATH/STOP_SOURCE_PATH";
const QString PUT_SOURCE_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_SOURCE_PATH";
const QString GET_SINKS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_SINKS_PATH";
const QString GET_SINK_INFO_PATH_KEY = "PULSAR_SERVICE_PATH/GET_SINK_INFO_PATH";
const QString GET_SINK_STATUS_PATH_KEY = "PULSAR_SERVICE_PATH/GET_SINK_STATUS_PATH";
const QString PUT_NEW_SINK_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_NEW_SINK_PATH";
const QString DELETE_SINK_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_SINK_PATH";
const QString PUT_SINK_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_SINK_PATH";
const QString START_SINK_PATH_KEY = "PULSAR_SERVICE_PATH/START_SINK_PATH";
const QString STOP_SINK_PATH_KEY = "PULSAR_SERVICE_PATH/STOP_SINK_PATH";
const QString GET_STORED_TOPIC_METADATA_KEY = "PULSAR_SERVICE_PATH/GET_STORED_TOPIC_METADATA";
const QString UPDATE_FUNCTION_PATH_KEY = "PULSAR_SERVICE_PATH/UPDATE_FUNCTION_PATH";
const QString GET_FUNCTION_INFO_PATH_KEY = "PULSAR_SERVICE_PATH/GET_FUNCTION_INFO_PATH";
const QString PRESTO_STATEMENT_PATH_KEY = "PULSAR_SERVICE_PATH/PRESTO_STATEMENT_PATH";
const QString PEEK_SUBSCRIPTION_MSG_PATH_KEY = "PULSAR_SERVICE_PATH/PEEK_SUBSCRIPTION_MSG_PATH";
const QString PUT_SUBSCRIPTION_PATH_KEY = "PULSAR_SERVICE_PATH/PUT_SUBSCRIPTION_PATH";
const QString DELETE_SUBSCRIPTION_PATH_KEY = "PULSAR_SERVICE_PATH/DELETE_SUBSCRIPTION_PATH";

#endif // CONSTANTS_H
